import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";

import "./globals.css";

const kumbhSans = Kumbh_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kumbhSans.className} mx-auto flex h-screen w-full max-w-7xl flex-col items-center justify-center bg-[#FAFAFA] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
